chore: modify changelog and format
deepin-community/yyjson pull request #3
Opened 2023-11-22 14:32 UTC by mhduiy

2023-11-22 14:32 UTC, mhduiy commented
@xzl01 原来的changelog能动吗，是不是应该新加一个log，改成合适的名字

2023-11-22 16:36 UTC, Rabenda commented on debian/source/format
> +4.0 (quilt)
https://wiki.debian.org/Projects/DebSrc3.0
参考材料 不要胡编乱造

2023-11-23 01:45 UTC, xzl01 requested changes
参照revy老师的意见修改

2023-11-23 14:35 UTC, mhduiy commented on debian/source/format
> +4.0 (quilt)
已经把错误的地方修改了，麻烦大佬看一下，新人维护，麻烦大佬多多指点\^o^/

2023-11-23 15:20 UTC, Rabenda approved these changes

2023-11-24 01:07 UTC, mhduiy commented
@xzl01

2023-11-24 01:41 UTC, xzl01 approved these changes

2023-11-24 01:41 UTC, merged